# -*- coding: utf-8 -*-
"""Text Summarization & Topic Modelling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XK9FEpCdslZgvzd0XqOUUUPI1mJGONEz
"""

!pip install transformers
from transformers import pipeline
summarizer = pipeline ("summarization", model="facebook/bart-large-cnn", truncation=True) ##set to True to truncate sequence to max permitted by the model

import requests
from bs4 import BeautifulSoup
''
url = "https://en.wikipedia.org/wiki/One_Hundred_and_One_Dalmatians"
res = requests.get(url)
html_page = res.content
soup = BeautifulSoup (html_page, 'html.parser')
text = ''
for paragraph in soup.find_all('p'):
  text += paragraph.text
#import package
import re
#clean text
text = re.sub(r'\[.*?\]+', '', text)
text = text.replace('\n','')
text

summary=summarizer(text, max_length=250, min_length=30, do_sample=False)
print(summary)